name: Build and Push Docker Image

env:
  IMAGE_REGISTRY: docker.io/
  IMAGE_REGISTRY_USER: umpalumpy
  IMAGE_REGISTRY_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
  VERSION: 1.0.0-SNAPSHOT

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      - name: Build with Maven
        run: mvn clean package

      - name: Build from Dockerfile
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: umpalumpy/management-back
          tags: ${{ env.VERSION }}
          dockerfiles: |
            ./Dockerfile

      - name: Push to registry
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.IMAGE_REGISTRY_USER }}
          password: ${{ env.IMAGE_REGISTRY_PASSWORD }}